-- MySQL Script generated by MySQL Workbench
-- 10/07/15 21:50:39
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Klant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Klant` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
  `voornaam` VARCHAR(45) NOT NULL COMMENT '',
  `achternaam` VARCHAR(45) NOT NULL COMMENT '',
  `emailadres` VARCHAR(45) NULL COMMENT '',
  `Adressen` VARCHAR(45) NULL COMMENT '',
  `rekeninggegevens` VARCHAR(45) NOT NULL COMMENT '',
  `Opmerkingen` TEXT NULL COMMENT '',
  `FacturenOpen` MEDIUMBLOB NULL COMMENT '',
  `FacturenBetaald` MEDIUMBLOB NULL COMMENT '',
  `OffertesOpen` MEDIUMBLOB NULL COMMENT '',
  `OffertjesArchief` MEDIUMBLOB NULL COMMENT '',
  `PlanStart` DATETIME NOT NULL COMMENT '',
  `PlanEind` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `idKlant_UNIQUE` (`id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Leverancier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Leverancier` (
  `idLeverancier` BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
  `Bedrijfsnaam` VARCHAR(45) NULL COMMENT '',
  `Contactpersoon` VARCHAR(45) NULL COMMENT '',
  `Emailadres` VARCHAR(45) NULL COMMENT '',
  `FacturenOpen` BLOB NULL COMMENT '',
  `FacturenBetaald` BLOB NULL COMMENT '',
  `Leveringen` VARCHAR(45) NULL COMMENT '',
  `Producten` VARCHAR(45) NULL COMMENT '',
  `Opmerkingen` TEXT NULL COMMENT '',
  PRIMARY KEY (`idLeverancier`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vloer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vloer` (
  `idVloer` BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
  `Type` VARCHAR(45) NULL COMMENT '',
  `Materiaal` VARCHAR(45) NULL COMMENT '',
  `AfmetingM2` INT NULL COMMENT '',
  `PrijsM2` INT NULL COMMENT '',
  PRIMARY KEY (`idVloer`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Adres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Adres` (
  `idAdres` BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
  `Straatnaam` VARCHAR(45) NOT NULL COMMENT '',
  `Huisnummer` INT NOT NULL COMMENT '',
  `Postcode` VARCHAR(6) NOT NULL COMMENT '',
  `Woonplaats` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idAdres`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product` (
  `idProduct` BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
  `Atikelnummer` INT NOT NULL COMMENT '',
  `Naam` VARCHAR(45) NOT NULL COMMENT '',
  `Omschrijving` BLOB NULL COMMENT '',
  `Type` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idProduct`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Productgroep`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Productgroep` (
  `idProductgroep` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Type` VARCHAR(8) NOT NULL COMMENT '',
  `Materiaal` VARCHAR(45) NOT NULL COMMENT '',
  `AfmetingM2` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idProductgroep`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Offerte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Offerte` (
  `idOfferte` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `VloerAantal` INT NOT NULL COMMENT '',
  `VloerPrijs` INT NOT NULL COMMENT '',
  `ProductAantal` INT NOT NULL COMMENT '',
  `ProductPrijs` INT NOT NULL COMMENT '',
  `TotaalPrijsInclBTW` INT NOT NULL COMMENT '',
  `TotaalprijsExclBTW` INT NULL COMMENT '',
  `Expiratiedatum` DATETIME NULL COMMENT '',
  `Opmerkingen` TEXT NULL COMMENT '',
  PRIMARY KEY (`idOfferte`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Werkbon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Werkbon` (
  `idWerkbon` BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
  `VloerAantal` INT NOT NULL COMMENT '',
  `ProductAantal` INT NOT NULL COMMENT '',
  `Opmerkingen` TEXT NOT NULL COMMENT '',
  PRIMARY KEY (`idWerkbon`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Factuur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Factuur` (
  `idOfferte` BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
  `VloerAantal` INT NOT NULL COMMENT '',
  `VloerPrijs` INT NOT NULL COMMENT '',
  `ProductAantal` INT NOT NULL COMMENT '',
  `ProductPrijs` INT NOT NULL COMMENT '',
  `TotaalPrijsInclBTW` INT NOT NULL COMMENT '',
  `TotaalprijsExclBTW` INT NULL COMMENT '',
  `Expiratiedatum` DATETIME NULL COMMENT '',
  `Opmerkingen` TEXT NULL COMMENT '',
  `idProduct` INT NOT NULL COMMENT '',
  `Klant_id` BIGINT NOT NULL COMMENT '',
  PRIMARY KEY (`idOfferte`)  COMMENT '',
  INDEX `fk_Factuur_Product1_idx` (`idProduct` ASC)  COMMENT '',
  INDEX `fk_Factuur_Klant1_idx` (`Klant_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Factuur_Product1`
    FOREIGN KEY (`idProduct`)
    REFERENCES `mydb`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factuur_Klant1`
    FOREIGN KEY (`Klant_id`)
    REFERENCES `mydb`.`Klant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Klant_Adres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Klant_Adres` (
  `Klant_idKlant` BIGINT NOT NULL COMMENT '',
  `Adres_idAdres` BIGINT NOT NULL COMMENT '',
  PRIMARY KEY (`Klant_idKlant`, `Adres_idAdres`)  COMMENT '',
  INDEX `fk_Klant_has_Adres_Adres1_idx` (`Adres_idAdres` ASC)  COMMENT '',
  INDEX `fk_Klant_has_Adres_Klant_idx` (`Klant_idKlant` ASC)  COMMENT '',
  CONSTRAINT `fk_Klant_has_Adres_Klant`
    FOREIGN KEY (`Klant_idKlant`)
    REFERENCES `mydb`.`Klant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Klant_has_Adres_Adres1`
    FOREIGN KEY (`Adres_idAdres`)
    REFERENCES `mydb`.`Adres` (`idAdres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vloer_has_Factuur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vloer_has_Factuur` (
  `Vloer_idVloer` BIGINT NOT NULL COMMENT '',
  `Factuur_idOfferte` BIGINT NOT NULL COMMENT '',
  PRIMARY KEY (`Vloer_idVloer`, `Factuur_idOfferte`)  COMMENT '',
  INDEX `fk_Vloer_has_Factuur_Factuur1_idx` (`Factuur_idOfferte` ASC)  COMMENT '',
  INDEX `fk_Vloer_has_Factuur_Vloer1_idx` (`Vloer_idVloer` ASC)  COMMENT '',
  CONSTRAINT `fk_Vloer_has_Factuur_Vloer1`
    FOREIGN KEY (`Vloer_idVloer`)
    REFERENCES `mydb`.`Vloer` (`idVloer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vloer_has_Factuur_Factuur1`
    FOREIGN KEY (`Factuur_idOfferte`)
    REFERENCES `mydb`.`Factuur` (`idOfferte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
